uploads = []
outputs = []

[[generated]]
id = "13wHofAh9dGKR2VgQbcX5"
uri = "file://artifacts/samsung-clone/src/assets/images/grid-tv.png"
type = "image"
title = "Premium OLED TV"

[[generated]]
id = "c6ZzZtv5Bzb6i4u0RF4Nh"
uri = "file://artifacts/samsung-clone/src/assets/images/grid-fridge.png"
type = "image"
title = "Smart refrigerator"

[[generated]]
id = "ynSl5zVLKbw4N4DtJZa8_"
uri = "file://artifacts/samsung-clone/src/assets/images/featured-tv.png"
type = "image"
title = "Featured cinematic OLED TV"

[[generated]]
id = "PdydGXxgaalBNNq2-Ale9"
uri = "file://attached_assets/generated_images/a_sleek_premium_smartphone_e2f3.png"
type = "image"
title = "generated_image"
